### ISSUE TITLE
Per PamGene request modify the default filename created as per core Export

### ISSUE THREAD

**Issue by makostadima** [tercen/export_table_operator#1]
@agouy so I created the following example to demonstrate the desired behaviour. I created an app that exports in two ways:

- with the old Export step
- with the new Export Table operator

The app can be found here: https://tercen.com/tercenTest/p/2d4a3c81ff96b26a3085562bb2b938f4
The apps default name is **App_with_Volcano_shiny_app_operator**.

I have then added the app in this workflow to display the behaviour of these two export steps: https://tercen.com/tercenTest/w/ddca1dfb0de22459bbea5aafe21c374c.

You will notice that after adding the above-mentioned app I modified its name to **my_new_app** and ran it!

Two outputs are created:
- one called **Export-Workflow test-my_new_app-Export 1** that is created by the core Export step and takes into consideration:
-- the name of the workflow the app has been added to (Workflow test in this case),
-- the new name of the app, called my_new_app, and
-- the name of the Export step called Export 1 (which might be important in case more than one Export steps exist within the app)
- one called **Export_App_with_Volcano_shiny_app_operator_-12/01/23-09:09:28.csv**  which is what I had manually defined in the Export Table data step during app development.

I hope that now it is clear.

**Comment by agouy** [comment]
0.1.1 will replace "WORKFLOW" and "DATASTEP" in the default file name by their respective values

**Comment by makostadima** [comment]
@agouy It's not exactly what she was after. Because the output now ignores the app/subworkflow name.

Notice that version 0.1.1 is now exporting a file called: **Exported_Table_Workflow test_Export 1-12/15/23-09:51:26.csv**, but the core Export step creates a file called **Export-Workflow test-my_new_app-Export 1**.

I am always looking at this workflow: https://tercen.com/tercenTest/w/ddca1dfb0de22459bbea5aafe21c374c
