### ISSUE TITLE
Export file does not have the Y-Axis factor name

### ISSUE THREAD

**Issue by martin1english** [tercen/export_table_operator#4]
The output file has the Column and row names correct but substitutes the Y-Axis factor name with (it looks like) a hard coded name.
![image](https://github.com/tercen/export_table_operator/assets/64135638/d63fff5c-1486-402d-824e-504b657fb681)

![image](https://github.com/tercen/export_table_operator/assets/64135638/e7d77e12-7bc5-4702-8392-6282e4c4b897)

**Comment by agouy** [comment]
This is fixed in version 0.2.6, thanks for reporting.
